steps:
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
- name: gcr.io/cloud-builders/docker
  args:
  - tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/scaife-viewer:$TAG_NAME
images:
- gcr.io/$PROJECT_ID/scaife-viewer:$TAG_NAME
