FROM node:10.15.3-alpine AS static
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci
COPY . /usr/src/app
RUN npm run lint
RUN npm run build

FROM python:3.7-alpine AS build
WORKDIR /usr/src/app
RUN pip install flake8
COPY . /usr/src/app
RUN flake8 scaife_viewer
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add build-base curl git libxml2-dev libxslt-dev linux-headers \
    && apk add postgresql-dev \
    && pip install psycopg2 \
    && apk del build-deps
COPY requirements.txt /
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt

FROM python:3.7-alpine
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add build-base curl git libxml2-dev libxslt-dev linux-headers \
    && apk add postgresql-dev \
    && pip install psycopg2 \
    && apk del build-deps
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY --from=build /wheels /wheels
COPY --from=build requirements.txt .
RUN pip install --no-cache /wheels/*
WORKDIR /usr/src/app
COPY --from=static ./usr/src/app/static/dist /usr/src/app/static/dist
COPY . /usr/src/app
