# pull official base image
FROM python:3.7-alpine

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set working directory
WORKDIR /usr/src/app

# install psycopg2
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add build-base curl git libxml2-dev libxslt-dev linux-headers \
    && apk add postgresql-dev \
    && pip install psycopg2 \
    && apk del build-deps

# install python dependencies
COPY requirements.txt /usr/src/app/requirements-dev.txt
RUN pip install -r requirements-dev.txt

# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# copy project
COPY . /usr/src/app/

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
