version: '3.2'

services:

  scaife-viewer:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    container_name: scaife-viewer
    entrypoint: /usr/src/app/entrypoint.sh
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=-!%+c%7ur9r#hpj3(9c_-u8nj7#*7+v+t(%-ks9(qj3mbq6f)=
      - DEBUG=0
      - DATABASE_URL=postgres://scaife:scaife@postgres:5432/postgres
      - ELASTICSEARCH_HOSTS=elasticsearch
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:10.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=scaife
      - POSTGRES_PASSWORD=scaife

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
