# pull official base image
FROM node:10.15.3-alpine

# set working directory
WORKDIR /usr/src/app

# install npm dependencies
COPY package-lock.json /usr/src/app/package-lock.json
COPY package.json /usr/src/app/package.json
RUN npm ci
RUN npm rebuild node-sass

# copy project
COPY . /usr/src/app/

# start webpack
CMD npm run start:docker
