# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('secret_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cloned_from', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reading.ReadingList')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reading list',
            },
        ),
        migrations.CreateModel(
            name='ReadingListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cts_urn', models.CharField(max_length=250)),
                ('resource_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reading.ReadingList')),
            ],
            options={
                'verbose_name': 'reading list entry',
                'verbose_name_plural': 'reading list entries',
            },
        ),
        migrations.CreateModel(
            name='ReadingListSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resource_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='reading.ReadingList')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reading list subscription',
                'verbose_name_plural': 'reading list subscriptions',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='readinglistentry',
            order_with_respect_to='resource_list',
        ),
    ]
