# Generated by Django 2.2.27 on 2022-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("release_url", models.URLField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "changelog entries",
            },
        ),
    ]
